"""Tests for the 4D Hopf phase-diagram experiment.

The full scan (31 × 21 × 4 cells) takes ~16 s on an M-series core; CI runs the
smoketest path with tiny grids (~0.05 s) to keep the suite snappy. The
production figure is generated by `python -m
reflexive_options.experiments.hopf_phase_scan_4d` and lives at
`paper/figures/hopf_phase_diagram.{pdf,png}`.
"""

from __future__ import annotations

import json
import sys
from collections.abc import Callable
from dataclasses import FrozenInstanceError
from pathlib import Path

import numpy as np
import pytest

from reflexive_options.experiments import hopf_phase_scan_4d
from reflexive_options.experiments.hopf_phase_scan_4d import (
    HopfScan4DConfig,
    main,
    plot_phase_diagram,
    run_4d_scan,
)


def _tiny_cfg() -> HopfScan4DConfig:
    """Smallest grid that exercises every code path in <100 ms."""
    return HopfScan4DConfig(
        n_kappa=51,
        n_xi=3,
        n_rho=3,
        sigma_v_slices=(0.5,),
    )


# ---------------------------------------------------------------------------
# Config invariants
# ---------------------------------------------------------------------------


def test_config_is_frozen() -> None:
    cfg = HopfScan4DConfig()
    with pytest.raises(FrozenInstanceError):
        cfg.n_kappa = 99  # type: ignore[misc]


def test_config_default_grid_dimensions() -> None:
    cfg = HopfScan4DConfig()
    assert cfg.n_kappa == 401
    assert cfg.n_xi == 31
    assert cfg.n_rho == 21
    assert cfg.sigma_v_slices == (0.10, 0.25, 0.50, 1.00)
    # Sanity on the (G_x, G_v, G_z) triplet — these are the canonical Hopf-
    # exhibiting values from paper/theory.md §4.2 and the figure assumes them.
    assert cfg.G_x == 0.5
    assert cfg.G_v == -0.5
    assert cfg.G_z == -0.5


# ---------------------------------------------------------------------------
# run_4d_scan — shape + Hopf-found contracts
# ---------------------------------------------------------------------------


def test_4d_scan_produces_correct_shapes() -> None:
    cfg = _tiny_cfg()
    xi_grid, rho_grid, sigma_v_slices, kappa_star_4d = run_4d_scan(cfg)
    assert xi_grid.shape == (cfg.n_xi,)
    assert rho_grid.shape == (cfg.n_rho,)
    assert sigma_v_slices.shape == (len(cfg.sigma_v_slices),)
    assert kappa_star_4d.shape == (cfg.n_xi, cfg.n_rho, len(cfg.sigma_v_slices))
    # Grids are linspace endpoints
    assert xi_grid[0] == cfg.xi_min
    assert xi_grid[-1] == cfg.xi_max
    assert rho_grid[0] == cfg.rho_min
    assert rho_grid[-1] == cfg.rho_max


def test_4d_scan_finds_hopf_at_default_parameters() -> None:
    """At the canonical Hopf-exhibiting regime (paper §4.2), most cells should
    have a finite κ*; in particular the central cell at (ξ=0.05–1.5 mid,
    ρ=0, σ_v=0.5) sits comfortably inside the Hopf wedge.
    """
    cfg = _tiny_cfg()
    _xi_grid, _rho_grid, _sigma_v, kappa_star_4d = run_4d_scan(cfg)
    # The (ρ=0, σ_v=0.5) midline reduces to the bare paper-§4.2 case where
    # κ* ≈ 0.86 (close to the published 0.8964 — small offset from the
    # ∂_v σ² = σ_v convention in `_shear_corrected_jacobian`).
    mid_xi = cfg.n_xi // 2
    mid_rho = cfg.n_rho // 2
    central = kappa_star_4d[mid_xi, mid_rho, 0]
    assert np.isfinite(central), f"central cell has no Hopf: {central}"
    assert 0.5 < central < 1.5, f"central κ* = {central} outside expected band"

    finite_fraction = np.mean(np.isfinite(kappa_star_4d))
    assert finite_fraction > 0.5, f"too many no-Hopf cells: {1 - finite_fraction:.1%}"


def test_4d_scan_sigma_v_slices_distinguishable() -> None:
    """Different σ_v slices should produce non-identical κ* grids — confirms
    the σ_v axis genuinely enters the Jacobian.
    """
    cfg = HopfScan4DConfig(
        n_kappa=51,
        n_xi=3,
        n_rho=3,
        sigma_v_slices=(0.1, 1.0),
    )
    _, _, _, kappa_star_4d = run_4d_scan(cfg)
    # At least one cell should differ between the two σ_v slices.
    diff = np.abs(kappa_star_4d[:, :, 0] - kappa_star_4d[:, :, 1])
    diff_finite = diff[np.isfinite(diff)]
    assert diff_finite.size > 0
    assert diff_finite.max() > 1e-3, "σ_v axis appears to be a no-op"


# ---------------------------------------------------------------------------
# Artifact persistence — npz, metrics.json, plot files
# ---------------------------------------------------------------------------


def test_4d_scan_writes_npz_and_json(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(hopf_phase_scan_4d, "make_run_dir", _stub_make_run_dir(tmp_path))
    fig_dir = tmp_path / "figures"
    fig_dir.mkdir()
    monkeypatch.setattr(hopf_phase_scan_4d, "FIGURES_DIR", fig_dir)
    monkeypatch.setattr(
        sys,
        "argv",
        ["hopf_phase_scan_4d", "--n-kappa", "51", "--n-xi", "3", "--n-rho", "3"],
    )

    main()

    children = sorted(p for p in tmp_path.iterdir() if p.is_dir() and p.name != "figures")
    assert len(children) == 1
    run_dir = children[0]

    # config.json round-trip
    cfg_payload = json.loads((run_dir / "config.json").read_text())
    assert cfg_payload["n_kappa"] == 51
    assert cfg_payload["n_xi"] == 3
    assert cfg_payload["n_rho"] == 3

    # metrics.json fields we depend on for the paper figure caption
    metrics = json.loads((run_dir / "metrics.json").read_text())
    for required_key in (
        "elapsed_seconds",
        "n_cells_total",
        "n_cells_with_hopf",
        "n_cells_no_hopf",
        "fraction_no_hopf",
        "median_kappa_star",
        "min_kappa_star",
        "max_kappa_star",
        "fastest_cell",
        "slowest_cell",
    ):
        assert required_key in metrics, f"metrics missing {required_key}"

    # npz round-trip with expected dtypes / shapes
    with np.load(run_dir / "phase_4d.npz") as npz:
        assert npz["xi_grid"].shape == (3,)
        assert npz["rho_grid"].shape == (3,)
        assert npz["sigma_v_slices"].shape == (4,)  # default slices
        assert npz["kappa_star_4d"].shape == (3, 3, 4)

    # Figure files
    assert (fig_dir / "hopf_phase_diagram.pdf").exists()
    assert (fig_dir / "hopf_phase_diagram.png").exists()
    assert (fig_dir / "hopf_phase_diagram.pdf").stat().st_size > 1_000


# ---------------------------------------------------------------------------
# Plot resilience — degenerate input shouldn't crash matplotlib
# ---------------------------------------------------------------------------


def test_plot_phase_diagram_handles_all_nan(tmp_path: Path) -> None:
    """If the scan finds no Hopf anywhere, the heatmap should still render
    (entirely white) without raising.
    """
    xi_grid = np.linspace(0.05, 1.5, 4)
    rho_grid = np.linspace(-0.95, 0.95, 5)
    sigma_v_slices = np.array([0.25, 0.5])
    kappa_star_4d = np.full((4, 5, 2), np.nan)

    pdf_path = tmp_path / "all_nan.pdf"
    png_path = tmp_path / "all_nan.png"
    plot_phase_diagram(
        xi_grid,
        rho_grid,
        sigma_v_slices,
        kappa_star_4d,
        pdf_path=pdf_path,
        png_path=png_path,
    )
    assert pdf_path.exists()
    assert png_path.exists()


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _stub_make_run_dir(root: Path) -> Callable[..., Path]:
    counter = {"n": 0}

    def _factory(experiment_name: str, *, seed: int | None = None) -> Path:
        counter["n"] += 1
        suffix = f"_seed{seed}" if seed is not None else ""
        run = root / f"{experiment_name}_{counter['n']:04d}{suffix}"
        run.mkdir(parents=True, exist_ok=True)
        return run

    return _factory
